### ISSUE TITLE
Question for packages in the ros-image-world

### ISSUE THREAD

**Issue by bchoineubility** [ros/meta-ros#1097]
Hi,

I have a question for ros-image-world.

Looking into ros-galactic packages supported by Ubuntu-20.04, there are some differences from ros-image-world in the galactic.

Can you please let me know how I can understand it correctly?

BR,
Mark

**Comment by robwoolley** [comment]
Hi Mark,

Galactic was last updated as part of milestone 17: https://github.com/ros/meta-ros/commit/4af30a62a39f1ce1fbc6c6a5c3e681ddc85ba0ee  It reached end of life on December 9th, 2022 ( https://docs.ros.org/en/rolling/Releases.html ).  Since it is no longer supported, I have not tried to update any of the recipes.

I intend to remove the unsupported sub-layers just prior to releasing Milestone 18.  They will still be available in the history if anyone needs them for historical reasons.  I am also happy to not remove the sub-layer and accept fixes if someone is willing to commit to maintaining it.

Regards,
Rob
