### ISSUE TITLE
webkit-gtk issue

### ISSUE THREAD

**Issue by prajankya** [ros/meta-ros#495]
I am getting a error for 

ERROR: Nothing PROVIDES 'webkit-gtk' (but build/../layers/meta-ros/recipes-extended/wxwidgets/wxwidgets_2.9.5.bb DEPENDS on or otherwise requires it). Close matches:
  webkitgtk
  webkit-efl

I have installed all the dependencies declared in the README of this repo. Is it in any other package ?

My dependency chain is ['mysoft', 'joint-state-publisher', 'wxpython', 'wxwidgets', 'webkit-gtk']

**Comment by bulwahn** [comment]
The joint-state-publisher, wxpython and wxwidgets recipes in meta-ros are not maintained anymore since quite some time. They were added by a contributor that is not active anymore, and we encountered an issue that we could not resolve in our available spare time. So, we removed the joint-state-publisher from our test builds, and simply left the existing recipes unmaintained for the first user to start investigating the needed work to get it building again.

**Comment by prajankya** [comment]
Thank you, I will try if I can.

**Comment by bulwahn** [comment]
Resolving the reported issue is however easy, just replace webkit-gtk with webkitgtk in the wxwidgets recipe. You will encounter more issues after that though.

**Comment by prajankya** [comment]
true, I am trying the same. Further and further issues, anyways, will get back to you with results asap.

**Comment by ioandev** [comment]
Hi, any updates on this?

**Comment by ioandev** [comment]
My logs: https://hastebin.com/zipedubofe.pas .

It just returns 1, no further explanation. I wonder if there would be an easy fix to it though.

**Comment by ioandev** [comment]
So i've managed to get wxwidgets running: https://github.com/bmwcarit/meta-ros/pull/549

But I still have problems getting wxpython to work.

What I've tried (very similar to what it's already there, just changed an include path):
https://hastebin.com/osatemurec.nginx

Resulting in:
https://hastebin.com/yixebiduxe.sql

I think I am missing a g++ flag?
